-- NextAuth-managed accounts in Supabase
--
-- The application authenticates with NextAuth (Credentials provider, JWT
-- sessions), not with Supabase Auth. public.profiles was written for Supabase
-- Auth: its id was a hard foreign key to auth.users, it had no column for a
-- credential, and row level security allowed only auth.uid() = id, so no
-- account row could ever be created by this app.
--
-- This migration turns public.profiles into the system of record for accounts:
-- the key is generated by the application, the bcrypt hash lives here, and the
-- service role is the only principal with access.
--
-- It deliberately adds no table for verification codes. Those are derived from
-- a keyed digest of the address and the current time window, so minting a code
-- and redeeming it agree without writing anything, which matters because the
-- two requests can reach different serverless instances.

-- ---------------------------------------------------------------------------
-- 1. Decouple public.profiles from auth.users
-- ---------------------------------------------------------------------------

-- Drop the foreign key to auth.users. Postgres derives the name from the
-- table and column, so profiles_id_fkey is not a guess. Until this is gone the
-- key still points at auth.users and inserting an application-generated id
-- fails, which is what the next statement is for.
ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_id_fkey;

-- The handle_new_user trigger fires on auth.users inserts and derives a role
-- from the email address. This app never inserts into auth.users, so it is dead
-- code that would only ever write rows without a credential. Supabase always
-- provides the auth schema.
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();

-- The credential. Nullable so this migration cannot fail against a database
-- that already holds profile rows; every row this application writes supplies
-- one. Tighten to NOT NULL once any legacy rows are reconciled.
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS password_hash TEXT;

-- ---------------------------------------------------------------------------
-- 2. Maintain updated_at
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.set_profiles_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := TIMEZONE('utc'::text, NOW());
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_profiles_updated_at ON public.profiles;
CREATE TRIGGER on_profiles_updated_at
BEFORE UPDATE ON public.profiles
FOR EACH ROW
EXECUTE PROCEDURE public.set_profiles_updated_at();

-- ---------------------------------------------------------------------------
-- 3. Restrict public.profiles to the service role
-- ---------------------------------------------------------------------------

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- These two compared against auth.uid(), which is always NULL without Supabase
-- Auth, so they granted nothing while implying that self-service reads existed.
DROP POLICY IF EXISTS "Users can read own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can insert own profile" ON public.profiles;

DROP POLICY IF EXISTS "Service role manages profiles" ON public.profiles;
CREATE POLICY "Service role manages profiles"
ON public.profiles
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);
